<?php
declare(strict_types=1);

/**
 * Static catalog service listings for catalog.php (same data as previous inline arrays).
 */
return [
    'ore' => [
        [
            'id' => 'gold-ore',
            'name' => 'Gold Ore Analysis',
            'category' => 'Precious Metals',
            'description' => 'Comprehensive gold content analysis using fire assay and atomic absorption spectroscopy (AAS) methods. Ideal for mining exploration and production quality control.',
            'methods' => ['Fire Assay', 'Atomic Absorption Spectroscopy', 'Gravimetric Analysis'],
            'turnaround' => '3-5 business days',
            'priority_turnaround' => '1-2 business days',
            'sample_size' => '50-100g minimum',
            'detection_limit' => '0.01 ppm',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'silver-ore',
            'name' => 'Silver Ore Analysis',
            'category' => 'Precious Metals',
            'description' => 'Accurate silver content determination for ore samples using fire assay and ICP-OES methods.',
            'methods' => ['Fire Assay', 'ICP-OES', 'Gravimetric Analysis'],
            'turnaround' => '3-5 business days',
            'priority_turnaround' => '1-2 business days',
            'sample_size' => '50-100g minimum',
            'detection_limit' => '0.5 ppm',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'copper-ore',
            'name' => 'Copper Ore Analysis',
            'category' => 'Base Metals',
            'description' => 'Complete copper grade determination and mineral composition analysis for mining operations and exploration projects.',
            'methods' => ['ICP-OES', 'XRF Analysis', 'Titration'],
            'turnaround' => '2-4 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '30-50g minimum',
            'detection_limit' => '0.01%',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'iron-ore',
            'name' => 'Iron Ore Analysis',
            'category' => 'Base Metals',
            'description' => 'Complete iron ore testing including total Fe content, FeO, silica, alumina, phosphorus, and trace element analysis.',
            'methods' => ['XRF Analysis', 'Titration', 'ICP-OES'],
            'turnaround' => '2-3 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '30-50g minimum',
            'detection_limit' => '0.01%',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'zinc-lead-ore',
            'name' => 'Zinc & Lead Ore Analysis',
            'category' => 'Base Metals',
            'description' => 'Multi-element analysis for zinc and lead ores including associated elements and impurity profiling.',
            'methods' => ['ICP-OES', 'AAS', 'XRF Analysis'],
            'turnaround' => '2-4 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '30-50g minimum',
            'detection_limit' => '0.01%',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'nickel-ore',
            'name' => 'Nickel Ore Analysis',
            'category' => 'Base Metals',
            'description' => 'Comprehensive nickel ore analysis including cobalt, magnesium, and other associated elements.',
            'methods' => ['ICP-OES', 'XRF Analysis', 'Gravimetric'],
            'turnaround' => '2-4 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '30-50g minimum',
            'detection_limit' => '0.01%',
            'accreditation' => 'ISO 17025',
        ],
    ],
    'liquid' => [
        [
            'id' => 'water-quality',
            'name' => 'Water Quality Testing',
            'category' => 'Environmental',
            'description' => 'Comprehensive water analysis for industrial, environmental, and drinking water compliance testing.',
            'methods' => ['ICP-MS', 'Ion Chromatography', 'Spectrophotometry'],
            'turnaround' => '1-2 business days',
            'priority_turnaround' => 'Same day',
            'sample_size' => '500ml minimum',
            'parameters' => 'pH, TDS, Heavy Metals, Anions, Cations',
            'accreditation' => 'ISO 17025, EPA Methods',
        ],
        [
            'id' => 'wastewater',
            'name' => 'Wastewater Analysis',
            'category' => 'Environmental',
            'description' => 'Industrial and municipal wastewater testing for regulatory compliance and treatment optimization.',
            'methods' => ['COD/BOD Analysis', 'ICP-OES', 'Spectrophotometry'],
            'turnaround' => '2-3 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '1L minimum',
            'parameters' => 'COD, BOD, TSS, Nutrients, Metals',
            'accreditation' => 'ISO 17025, EPA Methods',
        ],
        [
            'id' => 'oil-fuel',
            'name' => 'Oil & Fuel Analysis',
            'category' => 'Petroleum',
            'description' => 'Testing for petroleum products including viscosity, flash point, water content, and contamination levels.',
            'methods' => ['Viscometry', 'Karl Fischer', 'ICP-OES'],
            'turnaround' => '2-3 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '250ml minimum',
            'parameters' => 'Viscosity, Flash Point, Water Content, Metals',
            'accreditation' => 'ISO 17025, ASTM Methods',
        ],
        [
            'id' => 'lubricants',
            'name' => 'Lubricant Analysis',
            'category' => 'Petroleum',
            'description' => 'Used oil analysis and lubricant quality testing for equipment maintenance programs.',
            'methods' => ['ICP-OES', 'Viscometry', 'Particle Count'],
            'turnaround' => '1-2 business days',
            'priority_turnaround' => 'Same day',
            'sample_size' => '100ml minimum',
            'parameters' => 'Wear Metals, Viscosity, TAN/TBN, Contaminants',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'chemical-solutions',
            'name' => 'Chemical Solutions Analysis',
            'category' => 'Industrial',
            'description' => 'Analysis of chemical solutions for concentration, purity, and composition verification.',
            'methods' => ['Titration', 'ICP-OES', 'Spectrophotometry'],
            'turnaround' => '1-3 business days',
            'priority_turnaround' => '1 business day',
            'sample_size' => '100ml minimum',
            'parameters' => 'Concentration, Purity, Specific Gravity',
            'accreditation' => 'ISO 17025',
        ],
        [
            'id' => 'process-liquors',
            'name' => 'Process Liquor Analysis',
            'category' => 'Industrial',
            'description' => 'Mining and metallurgical process solution analysis for process control and optimization.',
            'methods' => ['ICP-OES', 'AAS', 'Titration'],
            'turnaround' => '1-2 business days',
            'priority_turnaround' => 'Same day',
            'sample_size' => '250ml minimum',
            'parameters' => 'Metal Content, Acid/Base, Free Cyanide',
            'accreditation' => 'ISO 17025',
        ],
    ],
];
